CREATE TABLE users(
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(200) UNIQUE,
	name VARCHAR(200),
	picture TEXT
);

CREATE TABLE access(
	id INT PRIMARY KEY AUTO_INCREMENT,
	user INT,
	auth_token VARCHAR(255) UNIQUE,
	CONSTRAINT FOREIGN KEY(user) REFERENCES users(id)
);
