CREATE TABLE users(
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(200) UNIQUE,
	name VARCHAR(200),
	picture TEXT,
	phone TEXT
);

CREATE TABLE access(
	id INT PRIMARY KEY AUTO_INCREMENT,
	user INT,
	auth_token VARCHAR(255) UNIQUE,
	CONSTRAINT FOREIGN KEY(user) REFERENCES users(id)
);

CREATE TABLE images(
	id INT PRIMARY KEY AUTO_INCREMENT,
	user INT,
	image_id VARCHAR(255) UNIQUE,
	placeholder VARCHAR(255),
	delivery_status ENUM('0','1') DEFAULT '0',
	delivery_time VARCHAR(255),
	CONSTRAINT FOREIGN KEY(user) REFERENCES users(id)
);
CREATE TABLE sms(
	id INT PRIMARY KEY AUTO_INCREMENT,
	`to` VARCHAR(255),
	message TEXT
);